对于复杂的神经网络和大规模的数据来说，使用cpu来计算可能不够高效。本节介绍如何使用GPU来计算。

### 计算设备

PyTorch可以指定用来存储和计算的设备。默认情况下，PyTorch会将数据创建在内存中，然后利用CPU来计算。

使用torch.cuda.is_available()查看GPU是否可用

In [1]:
import torch
from torch import nn

torch.cuda.is_available()

True

查看GPU数量

In [2]:
torch.cuda.device_count()

4

查看当前GPU索引号，索引号从0开始

In [3]:
torch.cuda.current_device()

0

根据索引号查看GPU名字

In [4]:
torch.cuda.get_device_name(0)

'GeForce RTX 2080 Ti'

### Tensor的GPU计算

使用.cuda(i)来表示使用第i块GPU及相应的显卡，且cuda(0)和cuda()等价。

In [5]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [6]:
x=x.cuda(1)
x

tensor([1, 2, 3], device='cuda:1')

我么可以通过Tensor的device属性来查看该Tensor所在的设备。

In [7]:
x.device

device(type='cuda', index=1)

我们可以直接在创建的时候就指定设备。

In [8]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x=torch.tensor([1,2,3],device=device)
#or x=torch.tensor([1,2,3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

**如果对在GPU上的数据进行运算那么结果还是存放在GPU上。需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在GPU上的数据不可以直接与存放在CPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的。**

### 模型的GPU计算

同Tensor类似，PyTorch模型也可以通过.cuda转换到GPU上。我们可以通过检查模型的参数的device属性来查看存放模型的设备。

In [9]:
net=nn.Linear(3,1)
list(net.parameters())[0].device

device(type='cpu')

将其转换到GPU上

In [10]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

**我们需要保证模型输入的Tensor和模型都在同一设备上，否则会报错。**